# Generated by Django 4.2.1 on 2023-06-29 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('savings_name', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('savings_balance', models.IntegerField()),
                ('reciepient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_reciepients', to=settings.AUTH_USER_MODEL)),
                ('savings_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saving_owners', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
