# Generated by Django 4.2.1 on 2023-06-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savings',
            name='savings_balance',
            field=models.IntegerField(default=0),
        ),
    ]
