# Generated by Django 4.2.1 on 2023-06-29 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0003_rename_savings_balance_savings_saved_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savings',
            old_name='saved_balance',
            new_name='savings_balance',
        ),
    ]
