# Generated by Django 4.2.1 on 2023-06-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0004_rename_saved_balance_savings_savings_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savings',
            name='savings_balance',
            field=models.IntegerField(null=True),
        ),
    ]
