# Generated by Django 4.2.1 on 2023-06-29 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0005_alter_savings_savings_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savings',
            old_name='savings_balance',
            new_name='balance',
        ),
    ]
