# Generated by Django 4.2.1 on 2023-06-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0006_rename_savings_balance_savings_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savings',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
