# Generated by Django 4.2.1 on 2023-06-30 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0009_savings_deadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savings',
            old_name='balance',
            new_name='amount_saved',
        ),
    ]
