# Generated by Django 4.2.1 on 2023-07-04 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_history', '0002_remove_history_transaction_id_history_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='transaction_description',
            field=models.TextField(null=True),
        ),
    ]
