# Generated by Django 4.2.1 on 2023-06-14 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alawi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('payment_sequence', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('initial_deposite', models.IntegerField(default=0)),
                ('product_balance', models.IntegerField(default=0)),
                ('product_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('reciepient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciepients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
