# Generated by Django 4.2.1 on 2023-06-16 06:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('alawi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alawi',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
