# Generated by Django 4.2.1 on 2023-06-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alawi', '0002_alter_alawi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='alawi',
            name='amount_to_be_paid',
            field=models.IntegerField(default=0),
        ),
    ]
