# Generated by Django 4.2.1 on 2023-07-02 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alawi', '0004_rename_product_owner_alawi_owner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alawi',
            old_name='owner_id',
            new_name='product_owner',
        ),
    ]
