# Generated by Django 4.2.1 on 2023-09-13 07:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alawi', '0005_rename_owner_id_alawi_product_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='alawi',
            name='payment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
