# Generated by Django 4.2.1 on 2023-09-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alawi', '0006_alawi_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alawi',
            name='payment_date',
            field=models.CharField(default='2023-09-25', max_length=50),
        ),
    ]
