# Generated by Django 4.2.1 on 2023-06-10 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tokenblacklist',
            old_name='token',
            new_name='access_token',
        ),
    ]
