# Generated by Django 4.2.1 on 2023-06-05 22:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_user_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dirth_of_birth',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
