# Generated by Django 4.2.1 on 2023-06-07 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_customuser_verification_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='dirth_of_birth',
            new_name='date_of_birth',
        ),
    ]
