# Generated by Django 4.2.1 on 2023-06-09 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_dirth_of_birth_customuser_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='verification_token',
        ),
    ]
