# Generated by Django 4.2.1 on 2023-06-10 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_customuser_verification_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='date_of_birth',
            new_name='dob',
        ),
    ]
