# Generated by Django 4.2.1 on 2023-06-20 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_customuser_verification_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='verification_token_created_at',
        ),
    ]
