# Generated by Django 4.2.1 on 2023-06-29 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_rename_verification_token_customuser_verifications_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='verifications_token',
            new_name='verification_token',
        ),
    ]
